version: "3.9"
services:
  db:
    build:
      context: ./
      dockerfile: ./mysql/Dockerfile
    ports:
      - "3306:3306"
    networks:
      - streams
  script:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/gisdata-python
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=batch
      - MYSQL_USER=user
      - MYSQL_PASSWORD=resu
    networks:
      - streams
    depends_on:
      - db
networks:
  streams: